"""StubAssistant — deterministic synthetic LLM for tests.

Used by `tests/test_llm_*.py` and the mocked pipeline test so the
LLM-using code paths can be exercised without a live OpenAI call.
"""

from __future__ import annotations

from typing import Any, Callable

from emc_assistant.llm.assistant import (
    LlmAssistant,
    LlmMode,
    ProblemContext,
    RecommendationDraft,
    RedactedSnippet,
)
from emc_assistant.parasitics.model import ParasiticEstimate
from emc_assistant.recommendations.engine import Recommendation


class StubAssistant(LlmAssistant):
    """Returns canned drafts that mention the snippet IDs it was given.

    Useful for asserting prompt construction and end-to-end flow.
    Records the last call's arguments for inspection in tests.

    For the M2.9 agent layer, tests can either set ``canned_completion``
    to a fixed string, or pass ``completion_callback(messages, purpose)``
    for per-call dynamic responses. ``complete_calls`` records every
    invocation so prompt construction can be asserted.
    """

    name = "stub"

    def __init__(
        self,
        *,
        canned_completion: str = "[]",
        completion_callback: Callable[[list[dict[str, Any]], str], str] | None = None,
    ) -> None:
        self.last_problem_context: ProblemContext | None = None
        self.last_parasitics: list[ParasiticEstimate] = []
        self.last_sim_metrics: dict[str, float] = {}
        self.last_snippets: list[RedactedSnippet] = []
        self.last_mode: LlmMode = "replace"
        self.last_baseline_recs: list[Recommendation] | None = None
        self.call_count: int = 0
        self.canned_completion = canned_completion
        self.completion_callback = completion_callback
        self.complete_calls: list[tuple[list[dict[str, Any]], str]] = []

    def complete(
        self,
        *,
        messages: list[dict[str, Any]],
        purpose: str,
        expected_output_tokens: int = 1500,
    ) -> str:
        self.complete_calls.append((list(messages), purpose))
        if self.completion_callback is not None:
            return self.completion_callback(messages, purpose)
        return self.canned_completion

    def explain_recommendations(
        self,
        *,
        problem_context: ProblemContext,
        parasitics: list[ParasiticEstimate],
        sim_metrics: dict[str, float],
        snippets: list[RedactedSnippet],
        mode: LlmMode = "replace",
        baseline_recs: list[Recommendation] | None = None,
    ) -> list[RecommendationDraft]:
        self.call_count += 1
        self.last_problem_context = problem_context
        self.last_parasitics = list(parasitics)
        self.last_sim_metrics = dict(sim_metrics)
        self.last_snippets = list(snippets)
        self.last_mode = mode
        self.last_baseline_recs = list(baseline_recs) if baseline_recs else None

        citations = [s.source_id for s in snippets[:3]]
        rule_ids = [s.rule_id for s in snippets[:3]]
        if mode == "augment" and baseline_recs is not None:
            return [
                RecommendationDraft(
                    id=r.id,
                    area=r.area,
                    severity=r.severity,
                    confidence=float(r.confidence),
                    problem=f"[stub-augmented] {r.problem}",
                    evidence=[f"[stub] cites {sid}" for sid in rule_ids] + list(r.evidence),
                    proposed_change=dict(r.proposed_change),
                    limitations=list(r.limitations),
                    sources=list(r.sources),
                    citations=citations,
                    llm_generated=True,
                    simulation_required=bool(r.simulation_required),
                    user_action=r.user_action,
                )
                for r in baseline_recs
            ]

        # replace mode — fabricate one synthetic rec
        return [
            RecommendationDraft(
                id="REC-001",
                area="testbench",
                severity="info",
                confidence=0.5,
                problem="[stub] Synthetic LLM-written recommendation.",
                evidence=[f"[stub] retrieved rule {rid}" for rid in rule_ids],
                proposed_change={
                    "type": "investigate",
                    "description": "Stub recommendation for tests.",
                },
                limitations=["Generated by StubAssistant — for testing only."],
                sources=rule_ids,
                citations=citations,
                llm_generated=True,
                simulation_required=True,
                user_action="Re-run with --llm openai to get real recommendations.",
            )
        ]
